#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

STASH_NAME="pre-commit-$(date +%s)"
git stash save -q --keep-index $STASH_NAME

./tools/test.sh
TEST_STATUS=$?

STASH_NUM=$(git stash list | grep $STASH_NAME | sed -E 's/stash@\{(.*)\}.*/\1/')
if [ -n "$STASH_NUM" ]; then
    git stash pop -q stash@{$STASH_NUM}
fi

exit $TEST_STATUS
