name:                www-justinmanley-work
version:             0.1.0.0
github:              "justinmanley/www-justinmanley-work"
license:             BSD3
author:              "Justin Manley"
maintainer:          "manleyjster@gmail.com"
copyright:           "2019 Justin Manley"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/www-justinmanley-work#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
  - src
  - projects
  other-modules:
  - Lifestory.Lifestory
  - Notegraph.Notegraph
  dependencies:
  - containers
  - directory
  - filepath
  - hakyll
  - text
  - url
  - xml
  - tagsoup


executables:
  site:
    main:                Site.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    dependencies:
    - aeson
    - binary
    - filepath
    - hakyll
    - text
    - unordered-containers
    - www-justinmanley-work

tests:
  www-justinmanley-work-test:
    main:                Test.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hakyll
    - hspec
    - www-justinmanley-work
    - xml
